#############################################################
####################### ULTRA GADGETS #######################
#############################################################

#Configuração:

#Debugg irá enviar informações a todo tempo sobre o plugin. (Recomendado = true)

System-Debugg: true

#Slot que o gadget será colocado quando player se juntar ao servidor. (0 = Slot 1, 8 = Slot 9)
Slot-Gadget-Join-Item: 0

#Slot do gadget. (0 = Slot 1, 8 = Slot 9)
Gadgets-Slot: 4

#Deixe 'true' para mostrar o gadget selecionado e outras informações na ActionBar (Textos cima do inventário)

Usar-ActionBar: true

#Títulos quando player recebe o gadget, ou o gadget ainda está em Cooldown
Usar-Titulos: true

#Som que será tocado quando o gadget ainda estiver em cooldown:
Som-Cooldown: NOTE_PLING

#Tempo em tickets dos titulos em:
FadeIn-Title-Time: 20
FadeStay-Title-Time: 50
FadeOut-Title-Time: 25

#Tempo de recarga dos Gadgets (Cooldown), a cada 1000 = 1 segundo. (10000 = 10s, 15000 = 15s, 20000 = 20s...)
#O cooldown padrão é o recomendado, o cooldown é resetado quando player reentrar no servidor.
#O cooldown muito baixo, pode causar um horrível desenpenho!

Bomba-Gadget-Cooldown: 15000
Cookie-Gadget-Cooldown: 32000
FunGun-Gadget-Cooldown: 2500
FireworkParty-Gadget-Cooldown: 28000
Movire-Gadget-Cooldown: 45000
StickTp-Gadget-Cooldown: 3000
Dj-Gadget-Cooldown: 72000
Disco-Gadget-Cooldown: 48000
RailGun-Gadget-Cooldown: 16000
SmokeBomb-Gadget-Cooldown: 26000
DiamondParty-Gadget-Cooldown: 35000
Paraquedas-Gadget-Cooldown: 38000
WitherShoot-Gadget-Cooldown: 35000
Trampolim-Gadget-Cooldown: 52000
Vampire-Gadget-Cooldown: 48000
VectorTNT-Gadget-Cooldown: 34000
ExplosiveSheep-Gadget-Cooldown: 12000

#Configuração dos gadgets:

#Máximo de blocos que o gadget "StickOfTeleport" poderá teleportar.
Area-Maxima-TpStick: 50

#Gadget vampiro pode voar?
Vampiro-Pode-Voar: true

#Você pode habiltiar ou desabilitar gadgets, pois alguns deles podem causar problemas.
Bomba-Gadget-Habilitar: true
Cookie-Gadget-Habilitar: true
FunGun-Gadget-Habilitar: true
FireworkParty-Gadget-Habilitar: true
Movire-Gadget-Habilitar: true
StickTp-Gadget-Habilitar: true
Dj-Gadget-Habilitar: true
Disco-Gadget-Habilitar: true
RailGun-Gadget-Habilitar: true
SmokeBomb-Gadget-Habilitar: true
DiamondParty-Gadget-Habilitar: true
Paraquedas-Gadget-Habilitar: true
WitherShoot-Gadget-Habilitar: true
Trampolim-Gadget-Habilitar: true
PaintballGun-Gadget-Habilitar: true
Vampire-Gadget-Habilitar: true
VectorTNT-Gadget-Habilitar: true
CowBoy-Gadget-Habilitar: true
MobGun-Gadget-Habilitar: true
ExplosiveSheep-Gadget-Habilitar: true